[package]
name = "rshipper"
version = "0.1.0"
authors = ["Hidde Bultsma <me@redodo.io>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
rand = "^0.7"
rand_core = "^0.5"
rand_chacha = "^0.2"
scrypt = "^0.3"
secrecy = "^0.7"
image = "^0.23"
rpassword = "^4.0"
zeroize = "^1.1"
